### ISSUE TITLE
Why this plugin dosen't work in my dokuwiki?

### ISSUE THREAD

**Issue by kevin2chen** [ghbore/flowchartjs#1]
I install the plugin to my dokuwiki successfully. But it dosen't work. I copied the code same as your example. After I submitted, page show a block of source code, not the flowchat view.

**Comment by doobidoo** [comment]
Same here

**Comment by kevin2chen** [comment]
@doobidoo I tried that diagramm, this is the code I wrote: 

`<flowchartjs default>
  st=>start: Start|past:>http://www.google.com[blank]
  e=>end: End|future:>http://www.google.com
  op1=>operation: My Operation|past
  op2=>operation: Stuff|current
  sub1=>subroutine: My Subroutine|invalid
  cond=>condition: Yes
  or No?|approved:>http://www.google.com
  c2=>condition: Good idea|rejected
  io=>inputoutput: catch something...|future
  st->op1(right)->cond
  cond(yes, right)->c2
  cond(no)->sub1(left)->op1
  c2(yes)->io->e
  c2(no)->op2->e
</flowchartjs>`

When I submitted, it showed the code between <flowchartjs></flowchartjs>, not a diagramm.

I use ubuntu12, php5.3, apache2.2.  I don't how to fix the problem

**Comment by konstruktur** [comment]
@kevin2chen: Try to remove the spaces in the beginning of each line. This worked for me

```
<flowchartjs>
st=>start: Start|past:>http://www.google.com[blank]
e=>end: End|future:>http://www.google.com
op1=>operation: My Operation|past
op2=>operation: Stuff|current
sub1=>subroutine: My Subroutine|invalid
cond=>condition: Yes
or No?|approved:>http://www.google.com
c2=>condition: Good idea|rejected
io=>inputoutput: catch something...|future
st->op1(right)->cond
cond(yes, right)->c2
cond(no)->sub1(left)->op1
c2(yes)->io->e
c2(no)->op2->e
</flowchartjs>
```


@ghbore: great job!

**Comment by kevin2chen** [comment]
@konstruktur Cool!!! It works.  Thank you!

**Comment by stko** [comment]
I tried the sample code above on an older and the actual dokuwiki version, but also without leading spaces it does not work..

**Comment by saseze** [comment]
Unfortunately the plugin is also not working in my (up-to-date) dokuwiki-environment.
I only get a blank area on the page after copying the example from the plugin-page or also using the example added some comments above. any good ideas?
The installation of the plugin was successfully - btw: should there be any options for this plugin in the admin-area of dokuwiki?

**Comment by ghbore** [comment]
@stko @saseze Could you provide the environment information where dokuwiki and this plugin run?  I will try hard to replicate the issues you have met, and figure out why.

Thank @kevin2chen for reporting this issue.   Thank @konstruktur and @doobidoo  for pointing out the reason for this.  I will fix this issue (trim leading blank in script.js) in days.

As far as I know, once the wiki code pass syntax check, there should be a block of source code (wrapped by \<pre\>); then once the flowchart.js render right, there should be an expected flowchart image.  If you got a blank area, hmm ... 

@saseze I first learn how to write admin plugin, and then add it to this plugin.

**Comment by saseze** [comment]
Thanks for your reply @ghbore and also thanks for your work building this plugin!
In meantime I was able to get the plugin and also the display of the flowchart running in my environment.
Previously I pasted the example into CKGEdit and this didn't work (blank area already described).
Now I simply pasted the example into the textfile of the page itself (notepad++) and afterwards the display was/is ok. I did some modifications on the flowchart-content in meantime and everything is working so far...

**Comment by ghbore** [comment]
Dear all,

I have updated this plugin.  The leading space issue has been solved by introduced up-to-date flowchart.js library which had add blank trimming.  Moreover I add admin plugin and toolbars to facilitate style manage.

Enjoy!

**Comment by stko** [comment]
Works like a charm :-)

Perfect !

Many thanks & best regards
Steffen

**Comment by ghbore** [comment]
@stko My pleasure!
