### ISSUE TITLE
Image in Dokuwiki too small

### ISSUE THREAD

**Issue by nop112233** [ghbore/flowchartjs#14]
When I do a Flowchart in Dokuwiki the size of the result ist very small.
`<flowchartjs default>
  st=>start: Start|past:>http://www.google.com[blank]
  e=>end: End|future:>http://www.google.com
  op1=>operation: My Operation|past
  op2=>operation: Stuff|current
  sub1=>subroutine: My Subroutine|invalid
  cond=>condition: Yes
  or No?|approved:>http://www.google.com
  c2=>condition: Good idea|rejected
  io=>inputoutput: catch something...|future
  st->op1(right)->cond
  cond(yes, right)->c2
  cond(no)->sub1(left)->op1
  c2(yes)->io->e
  c2(no)->op2->e
</flowchartjs>`

**Comment by IcEPiQQ** [comment]
same to me, but I solved it:
install flowcharts Plugin von [ Jakob Schwichtenberg]
In there is an css override provided, called mermaid-override.css - located in ..\dokuwiki\lib\plugins\flowcharts\
in that CSS add 
.flowchartjs svg {
	width: 100%;
	height: 160vh; /* Causes schema to fill 160% of the viewable height. */
}

that´s it

**Comment by ghbore** [comment]
Hi guys, apologize for not maintaining this plugin for years. Recently I came across the repo, and thank you for pointing out the solution for this issue. I have implemented an update and it should work right now.
