### ISSUE TITLE
Warnings after Dokuwiki Install

### ISSUE THREAD

**Issue by wrperin** [ghbore/flowchartjs#2]
I'm getting Warnings when I install your plugin on my Dokuwiki. They appear on other pages too.

`Warning: Declaration of syntax_plugin_flowchartjs::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in ...wiki/lib/plugins/flowchartjs/syntax.php on line 59

Warning: Declaration of syntax_plugin_flowchartjs::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in ...wiki/lib/plugins/flowchartjs/syntax.php on line 59

Warning: Cannot modify header information - headers already sent by (output started at ...wiki/lib/plugins/flowchartjs/syntax.php:59) in ...wiki/inc/actions.php on line 210

Warning: Cannot modify header information - headers already sent by (output started at ...wiki/lib/plugins/flowchartjs/syntax.php:59) in ...wiki/lib/tpl/dokuwiki/main.php on line 12`

**Comment by ghbore** [comment]
Hi, does those warnings prevent you from smooth usage of this plugin? If they do, could you provide more information about the environment you installed this plugin.  I followed the developer instructions from dokuwiki website, and have not encountered this kind of warnings or errors.

**Comment by zchtoy** [comment]
I had solved this issue
function handle($match, $state, $pos, &$handler)
change to 
function handle($match, $state, $pos, $handler)

function render($mode, &$renderer, $data)
change to 
function render($mode, $renderer, $data)

**Comment by ghbore** [comment]
Thank you, @zchtoy and @wrperin
