### ISSUE TITLE
compatibility to dw2pdf?

### ISSUE THREAD

**Issue by Thatsreallycool** [ghbore/flowchartjs#3]
Not a bug report, but a feature request: Could you make it possible to export the flow chart from dw to pdf for example over dw2pdf?

**Comment by ghbore** [comment]
I have investigated dw2pdf plugin, and found dw2pdf did not use javascript on export (see [dw2pdf issue 40](https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/issues/40)). While flowchartjs plugin requires javascript libraries to replace diagram by svg image.

Why not export wiki page into pdf through browser's print button? That works.
