### ISSUE TITLE
PHP 7.0 compliance

### ISSUE THREAD

**Issue by jankokert** [ghbore/flowchartjs#6]
Warning: Declaration of syntax_plugin_flowchartjs::handle($match, $state, $pos, $handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /volume1/web/dokuwiki/lib/plugins/flowchartjs/syntax.php on line 0

Warning: Declaration of syntax_plugin_flowchartjs::render($mode, $renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /volume1/web/dokuwiki/lib/plugins/flowchartjs/syntax.php on line 0

To fix this please change in syntax.php line 30 to:
`	function handle($match, $state, $pos, Doku_Handler $handler){`

and line 41 to:
`	function render($mode, Doku_Renderer $renderer, $data) {`

**Comment by ghbore** [comment]
Thank you @CubaLibre84. I just fix it.
