### ISSUE TITLE
Can the size of the generated chart been adapted to the dokuwiki width?

### ISSUE THREAD

**Issue by stko** [ghbore/flowchartjs#7]
Hi
the generated chart does not care about the view width of the surrounding dokuwiki page, so whenever it exceeds the view width, it becomes partly invisible and so lost its sense :-(

Could it be made somehow that the chart is somehow "squeezed" into the available width and becomes fully visible, just smaller?

thanks for your help :-)

regards
Steffen
![image](https://user-images.githubusercontent.com/4143790/59692657-badb8e00-91e5-11e9-939a-11669d058fe7.png)

**Comment by ghbore** [comment]
Dear Steffen,

I have updated this plugin to support extra parameters following **style** to control the view **width** and **height**. In your case, you can add '100%' in the flowchartjs tag, for example:

`<flowchartjs your_style 100%>
...
</flowchartjs>`

**Comment by stko** [comment]
Dear Gao

thanks for your incredible quick response! I've installed the latest software by downloading the github zip file and copy all files into the Dokuwiki flowchartjs plugin directory by overwrite all old files, but it does not show the expected effect: Even if I set the scale to a quite low percentage rate, it still shows the diagram in the original full size:


![image](https://user-images.githubusercontent.com/4143790/59739006-92927480-9263-11e9-8d22-2a8bd6888ee1.png)


Something is going wrong. Can I support you anyhow in the fault finding?

regards
Steffen

**Comment by ghbore** [comment]
Dear Steffen,

You can try to remove the browser cache before refreshing the wiki page.

Once it works, you can see the **width** attribute has been changed as provided.
![my try](https://user-images.githubusercontent.com/9670777/59740489-d48add00-929a-11e9-98d6-ff0eecaf807a.png)

If it's still not working, you'd better remove this plugin first and then install/update this plugin through extension manager. Maybe the extension manager will automaticly fresh site-side javascript.

Good luck~
Hua

**Comment by stko** [comment]
After Clear cache it works ! :-)  Probably the old javascript was still in the cache 

Many Thanks!
Steffen
