### ISSUE TITLE
Direction Indicators not Always Honored

### ISSUE THREAD

**Issue by diadz** [ghbore/flowchartjs#9]
I've got a flowchart that renders properly when I paste the text definition in at http://flowchart.js.org/, but when I plug the exact same text in on my Dokuwiki site, one of the direction indicators is being ignored and results in an ugly flowchart.

The relevant connector definition is as follows:

cnPassInspect(yes,left)->opMoveToStock->end
cnPassInspect(no)->opMoveMRB->opNotifyBuyer(left)->end

Below are screenshots showing the relevant node and how the connectors are being rendered in my Dokuwiki (1st image) compared to flowcharts.js.org (2nd image.)

![bad](https://user-images.githubusercontent.com/72579146/95511649-9a9c8900-096c-11eb-9cf7-26c5c49d8361.jpg)
![good](https://user-images.githubusercontent.com/72579146/95511948-fc5cf300-096c-11eb-97d3-f75db8337eb2.jpg)

Do you have any ideas as to what the problem is and how I can correct this?

Thanks for building this plugin and for any assistance you can provide with this issue.

**Comment by ghbore** [comment]
Hi @diadz. I can not repeat the bug you have met without the full piece of flowchart definition. Though, the main difference between official flowchart.js and DokuWiki flowchartjs plugin is the version of the flowchart library. So I have updated the version to be the same. Hope this can help solve the problem.

**Comment by diadz** [comment]
@ghbore, that was it. Everything looks good now. Thanks for the quick fix!
